### ISSUE TITLE
error buld example django-app

### ISSUE THREAD

**Issue by stilet** [tbeadle/docker-gunicorn#2]
db uses an image, skipping
Building ui
Step 1/1 : FROM tbeadle/gunicorn-nginx:3.6-onbuild
# Executing 4 build triggers
 ---> Using cache
 ---> Running in 6fee375103a1
----> Running /app/docker/pre-build.d/01_build_time_deps.sh
Installing build time dependencies.
Get:1 http://security.debian.org stretch/updates InRelease [94.3 kB]
Ign:2 http://deb.debian.org/debian stretch InRelease
Get:3 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://security.debian.org stretch/updates/main amd64 Packages [481 kB]
Get:6 http://deb.debian.org/debian stretch Release.gpg [2,434 B]
Get:7 http://deb.debian.org/debian stretch-updates/main amd64 Packages [5,476 B]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [9,500 kB]
Fetched 10.3 MB in 3s (3,105 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package postgresql-client-9.4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'postgresql-client-9.4' has no installation candidate
ERROR: Service 'ui' failed to build: The command '/bin/sh -c build_app.sh' returned a non-zero code: 100

**Comment by tbeadle** [comment]
Fixed in https://github.com/tbeadle/docker-gunicorn/commit/bb816033a6690f5169fb79b53656d1aae5a87272
